name: Go Build

permissions:
  "contents": "write"

on:
  push:
    branches: ["master", "main"]
  pull_request:
    branches: ["master", "main"]

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]
        include:
          - os: ubuntu-latest
            output: twitch-follows-to-discord
          - os: macos-latest
            output: twitch-follows-to-discord
          - os: windows-latest
            output: twitch-follows-to-discord.exe
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version: "1.26.3"
      - name: Build
        run: go build -o ${{ matrix.output }} .
      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          name: twitch-follows-to-discord-${{ matrix.os }}
          path: ${{ matrix.output }}
  create-release:
    needs: [build]
    runs-on: ubuntu-latest
    if: (github.event_name == 'push' && github.ref == 'refs/heads/main')

    steps:
      - uses: actions/checkout@v6
        name: Checkout Code

      # Windows
      - uses: actions/download-artifact@v8
        name: Download Windows
        with:
          name: twitch-follows-to-discord-windows-latest
          path: release-artifacts/

      - name: Rename Windows Binary
        run: mv release-artifacts/twitch-follows-to-discord.exe release-artifacts/twitch-follows-to-discord-Windows.exe

      - uses: actions/download-artifact@v8
        name: Download Linux
        with:
          name: twitch-follows-to-discord-ubuntu-latest
          path: release-artifacts/

      - name: Rename Linux Binary
        run: mv release-artifacts/twitch-follows-to-discord release-artifacts/twitch-follows-to-discord-Linux

      - uses: actions/download-artifact@v8
        name: Download Mac
        with:
          name: twitch-follows-to-discord-macos-latest
          path: release-artifacts/

      - name: Rename Mac Binary
        run: mv release-artifacts/twitch-follows-to-discord release-artifacts/twitch-follows-to-discord-Mac

      - name: Create release
        uses: ncipollo/release-action@v1.21.0
        with:
          replacesArtifacts: true
          allowUpdates: true
          artifactErrorsFailBuild: true
          artifacts: "release-artifacts/*"
          body: ${{ github.event.head_commit.message }}
          prerelease: true
          name: Nightly Release
          tag: nightly-build

      - name: Update nightly-build tag
        run: |
          git tag -f nightly-build
          git push -f origin nightly-build
        shell: bash
